version: '3.8'

services:
    mysql:
        image: mysql:5
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - 3307:3306
        volumes:
            - data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: wastebin
            MYSQL_DATABASE: wastebin
            MYSQL_USER: wastebin
            MYSQL_PASSWORD: wastebin

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

volumes:
    data:
